# Generated by Django 6.0.8 on 2026-08-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('SUBSCRIPTION', 'Subscription'), ('MUSIC', 'Music'), ('FOLLOW', 'Follow'), ('SUPPORT', 'Support'), ('PAYOUT', 'Payout')], default='SYSTEM', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', help_text='Frontend route to navigate to', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
