# Generated by Django 6.0.8 on 2026-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic (Free)'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=10, unique=True),
        ),
    ]
