# Generated by Django 6.0.8 on 2026-08-15 20:20

from django.db import migrations


def rename_tiers_forward(apps, schema_editor):
    """Rename old tier values to match project document."""
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    mapping = {
        'FREE': 'BASIC',
        'REGULAR': 'SILVER',
        'PREMIUM': 'GOLD',
    }
    for old, new in mapping.items():
        SubscriptionPlan.objects.filter(tier=old).update(tier=new)
    # Remove tiers that no longer exist in the spec
    SubscriptionPlan.objects.filter(tier__in=['FAMILY', 'STUDENT']).delete()


def rename_tiers_reverse(apps, schema_editor):
    """Reverse the rename."""
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    mapping = {
        'BASIC': 'FREE',
        'SILVER': 'REGULAR',
        'GOLD': 'PREMIUM',
    }
    for old, new in mapping.items():
        SubscriptionPlan.objects.filter(tier=old).update(tier=new)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_align_tiers_to_project_doc'),
    ]

    operations = [
        migrations.RunPython(rename_tiers_forward, rename_tiers_reverse),
    ]
