# Generated by Django 6.0.8 on 2026-08-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_tier_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
