# Generated by Django 6.0.8 on 2026-08-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_offset_days', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
