# Generated by Django 6.0.8 on 2026-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
