# Generated by Django 6.0.8 on 2026-08-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('release_date', models.DateField()),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('audio_file', models.FileField(upload_to='tracks/')),
                ('release_date', models.DateField()),
                ('release_type', models.CharField(choices=[('SINGLE', 'Single'), ('ALBUM', 'Album')], default='SINGLE', max_length=6)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('collaborators', models.TextField(blank=True, default='')),
                ('file_format', models.CharField(choices=[('MP3', 'MP3'), ('WAV', 'WAV'), ('FLAC', 'FLAC')], default='MP3', max_length=4)),
                ('is_early_access', models.BooleanField(default=False)),
                ('listeners_count', models.IntegerField(default=0)),
                ('total_streams', models.IntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_logs', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_logs', to='music.track')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'streamed_at'], name='music_strea_user_id_d85f8a_idx'), models.Index(fields=['track', 'streamed_at'], name='music_strea_track_i_96cec7_idx')],
            },
        ),
    ]
