# Generated by Django 6.0.8 on 2026-08-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-release_date', '-id']},
        ),
    ]
