# Generated by Django 6.0.8 on 2026-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_track_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file_128',
            field=models.FileField(blank=True, null=True, upload_to='tracks_128/'),
        ),
    ]
