# Generated by Django 6.0.8 on 2026-08-16 23:47

import subscriptions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_audio_file_128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamlog',
            name='streamed_at',
            field=models.DateTimeField(default=subscriptions.utils.get_current_time),
        ),
    ]
